[build]
  base = "frontend"
  command = "npm ci && npm run build && cd ../backend && npm ci"
  publish = "frontend/build"

[functions]
  directory = "backend/functions"
  external_node_modules = ["express", "serverless-http"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
